name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rust fmt
      run: |
        shopt -s globstar
        rustfmt **/*.rs --check
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
  why3:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Use OCaml ${{ env.OCAML_COMPILER }}
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ env.OCAML_COMPILER }}
    - name: Install Alt-Ergo
      run: opam install alt-ergo.2.4.1
    - name: Install Z3
      run: sudo apt-get install -y z3=4.8.12-1 cvc4=1.8-2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: dawidd6/action-download-artifact@v2
      with:
        workflow: why3.yml
        name: why3
        path: /home/runner/work/creusot/why3
    - run: |
        chmod -R +x ~/work/creusot/why3/bin
        chmod -R +x ~/work/creusot/why3/lib/why3/why3server
        eval $(opam env)
        ~/work/creusot/why3/bin/why3 config detect
        cat ~/.why3.conf
    - run: cargo test --test why3 "" -- --lazy
      env:
        WHY3_CONFIG: ${{ github.workspace }}/ci/why.conf
        WHY3_PATH: ${{ github.workspace }}/../why3/bin/why3
    - run: cargo test --test why3
      env:
        WHY3_CONFIG: ${{ github.workspace }}/ci/why.conf
        WHY3_PATH: ${{ github.workspace }}/../why3/bin/why3
